# action.yml
name: 'Decomposer report'
description: 'Report dependencies to GitHub'
inputs:
  target-dir:
    description: Dependency directory
    required: true
  github-token:
    description: Token to use in GH API calls
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip3 install -r $GITHUB_ACTION_PATH/requirements.txt

    - name: Report decomposer dependencies
      shell: bash
      working-directory: ${{ github.workspace }}
      env:
        TARGET_DIR: ${{ inputs.target-dir }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        source .venv/bin/activate
        python3 $GITHUB_ACTION_PATH/main.py
