# action.yml
name: 'Reviewboard'
description: 'Check if there is a review and if it has ship-its'
inputs:
  reviewboard_token:
    description: Reviewboard token
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        pip3 install -r $GITHUB_ACTION_PATH/requirements.txt

    - name: Run Reviewboard check
      env:
        RB_TOKEN: ${{ inputs.reviewboard_token }}
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |
        source .venv/bin/activate
        python3 $GITHUB_ACTION_PATH/main.py
